apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "secret.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}
type: {{ default ("Opaque") .Values.type }}
{{- if .Values.data }}
data:
  {{- toYaml .Values.data | nindent 2 }}
{{- else if .Values.stringData }}
stringData:
  {{- toYaml .Values.stringData | nindent 2 }}
{{- end }}
{{- if .Values.immutable }}
immutable: true
{{- end }}
